// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"

import SliderController from "./slider_controller";

import GeolocationController from "./geolocation_controller";
import HumburgerController from "./humburger_controller";

application.register("slider", SliderController)
application.register("hello", HelloController)
application.register("geolocation", GeolocationController)
application.register("humburger", HumburgerController)
